"""create initial tables

Revision ID: b3b483280681
Revises: xxxx_add_carts_and_product_plans
Create Date: 2026-02-08 14:06:50.213984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b3b483280681'
down_revision: Union[str, Sequence[str], None] = 'xxxx_add_carts_and_product_plans'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blog_category', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('blog_category', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
    op.alter_column('blog_category', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
    # op.drop_index(op.f('ix_blog_category_is_active'), table_name='blog_category')
    # op.drop_index(op.f('ix_blog_category_name'), table_name='blog_category')
    # op.drop_index(op.f('uq_blog_category_slug'), table_name='blog_category')
    # op.drop_index(op.f('ix_blog_posts_category_id'), table_name='blog_posts')

    #op.drop_index(op.f('ix_blog_posts_category_id'), table_name='blog_posts')
    op.alter_column('orders', 'status',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('orders', 'admin_status',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('orders', 'payment_status',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.drop_index(op.f('fk_products_duration_types'), table_name='products')
    op.drop_constraint(op.f('fk_products_duration_type_id'), 'products', type_='foreignkey')
    op.drop_constraint(op.f('fk_products_subscription_type_id'), 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'duration_types', ['duration_type_id'], ['id'])
    op.create_foreign_key(None, 'products', 'subscription_types', ['subscription_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key(op.f('fk_products_subscription_type_id'), 'products', 'subscription_types', ['subscription_type_id'], ['id'], onupdate='CASCADE')
    op.create_foreign_key(op.f('fk_products_duration_type_id'), 'products', 'duration_types', ['duration_type_id'], ['id'], onupdate='CASCADE')
    op.create_index(op.f('fk_products_duration_types'), 'products', ['duration'], unique=False)
    op.alter_column('orders', 'payment_status',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('orders', 'admin_status',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('orders', 'status',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.create_index(op.f('ix_blog_posts_category_id'), 'blog_posts', ['category_id'], unique=False)
    op.drop_index(op.f('ix_blog_category_slug'), table_name='blog_category')
    op.create_index(op.f('uq_blog_category_slug'), 'blog_category', ['slug'], unique=True)
    op.create_index(op.f('ix_blog_category_name'), 'blog_category', ['name'], unique=False)
    op.create_index(op.f('ix_blog_category_is_active'), 'blog_category', ['is_active'], unique=False)
    op.alter_column('blog_category', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
    op.alter_column('blog_category', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
    op.alter_column('blog_category', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text('1'))
    # ### end Alembic commands ###
