"""add duration/subscription/personal_account to order_items

Revision ID: db77bb5bdf8a
Revises: 6779e84c9db1
Create Date: 2026-02-09 10:39:09.798280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db77bb5bdf8a'
down_revision: Union[str, Sequence[str], None] = '6779e84c9db1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_index(op.f('ix_blog_posts_category_id'), table_name='blog_posts')
    op.add_column('order_items', sa.Column('duration_type_id', sa.Integer(), nullable=True))
    op.add_column('order_items', sa.Column('subscription_type_id', sa.Integer(), nullable=True))
    op.add_column('order_items', sa.Column('personal_account', sa.Boolean(), nullable=False))
    op.create_foreign_key(None, 'order_items', 'subscription_types', ['subscription_type_id'], ['id'])
    op.create_foreign_key(None, 'order_items', 'duration_types', ['duration_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.drop_column('order_items', 'personal_account')
    op.drop_column('order_items', 'subscription_type_id')
    op.drop_column('order_items', 'duration_type_id')
    op.create_index(op.f('ix_blog_posts_category_id'), 'blog_posts', ['category_id'], unique=False)
    # ### end Alembic commands ###
